create table if not exists public.packages(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,price_minor bigint not null,service_id uuid references public.services(id),total_uses integer not null,expires_days integer,created_at timestamptz not null default now(),active boolean not null default true);
create table if not exists public.package_usage(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,package_id uuid not null references public.packages(id),customer_id uuid not null references public.customers(id),appointment_id uuid references public.appointments(id),used_at timestamptz not null default now());
create table if not exists public.memberships(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,price_minor bigint not null,discount_percent numeric(5,2) not null default 0,duration_days integer not null,active boolean not null default true);
create table if not exists public.customer_memberships(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,membership_id uuid not null references public.memberships(id),customer_id uuid not null references public.customers(id),starts_at timestamptz not null,ends_at timestamptz not null,status text not null default 'active');
create table if not exists public.loyalty_accounts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,customer_id uuid not null unique,points bigint not null default 0,created_at timestamptz not null default now());
create table if not exists public.loyalty_transactions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,customer_id uuid not null references public.customers(id),points_delta bigint not null,reason text not null,appointment_id uuid references public.appointments(id),created_at timestamptz not null default now());
create table if not exists public.coupons(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,code text not null,discount_percent numeric(5,2),discount_minor bigint,expires_at timestamptz,usage_limit integer,usage_count integer not null default 0,active boolean not null default true,unique(organization_id,code));
create table if not exists public.campaigns(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,segment text not null,channel text not null check(channel in ('push','email','sms')),message text not null,status text not null default 'draft',scheduled_at timestamptz,sent_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.campaign_recipients(id uuid primary key default gen_random_uuid(),campaign_id uuid references public.campaigns(id) on delete cascade,customer_id uuid references public.customers(id),opened_at timestamptz,booked_at timestamptz);

create or replace function public.award_loyalty_for_payment(p_payment uuid) returns void language plpgsql security definer set search_path=public as $$
declare v_org uuid; v_customer uuid; v_amount bigint; v_points bigint; begin select p.organization_id,a.customer_id,p.amount_minor into v_org,v_customer,v_amount from payments p join appointments a on a.id=p.appointment_id where p.id=p_payment and p.type='payment' and p.status='completed'; if v_org is null then return; end if; v_points=floor(v_amount/100); insert into loyalty_accounts(organization_id,customer_id,points) values(v_org,v_customer,v_points) on conflict(customer_id) do update set points=loyalty_accounts.points+excluded.points; insert into loyalty_transactions(organization_id,customer_id,points_delta,reason,appointment_id) select v_org,v_customer,v_points,'spend',appointment_id from payments where id=p_payment; end $$;

create or replace function public.customer_segment(p_org uuid,p_segment text) returns table(customer_id uuid) language sql stable security definer set search_path=public as $$
select c.id from customers c where c.organization_id=p_org and c.deleted_at is null and case p_segment when 'inactive_30' then coalesce(c.last_visit_at,'1900-01-01') < now()-interval '30 days' when 'vip' then c.total_spent_minor >= 100000 when 'frequent_no_show' then c.no_show_count >= 3 when 'first_visit' then c.last_visit_at is null else false end;
$$;
